name: Generate terraform docs
on:
  push:
    branches:
      - main
      - test/*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./,examples
        output-file: README.md
        output-method: replace
        git-push: true
        fail-on-diff: true
