name: Test
on:
  push:
    branches:
      - main
      - develop

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      # - name: Init and Apply terraform
      #   run: |
      #     cd ./dir
      #     terraform init
      #     terraform apply --auto-approve

      - name: Debug 
        run: |
          DIR="$(mktemp -d)"
          cp dummy.tf "$DIR"
          cd "$DIR"
          terraform init && terraform apply --auto-approve
      
      - name: Run my action
        uses: ./
        # with:
        #   work_dir: './dir'