name: Test
on:
  push:
    branches:
      - main
      - develop

jobs:
  run-action:
    name: Run action
    runs-on: ['self-hosted', 'Linux', 'x64']

    steps:
      - uses: actions/checkout@v2

      # - name: Use Node.js 14.xz
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14.x
      #     cache: 'npm'
      #     cache-dependency-path: package-lock.json

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build
      #   run: npm run build

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.1.7

      # - name: Init and Apply terraform
      #   run: |
      #     cd ./dir
      #     terraform init
      #     terraform apply --auto-approve
      
      - name: Debug
        run: |
          echo $HOME
          ls -la

      - name: Init and apply terraform 
        run: |
          DIR="bla"
          cp dummy.tf "$DIR"
          cd "$DIR"
          terraform init && terraform apply --auto-approve
          echo "::set-output name=dir::$DIR"

      - name: Run my action
        uses: ./
        with:
          work_dir: '/'